version: '2'
services:
  mariadb:
    image: bitnami/mariadb:10.3.32
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: bitnami/wordpress:5.8.3
    ports:
      - '8000:8080'
      - '8443:8443'
    depends_on:
      - mariadb
    volumes:
      - ./data:/bitnami/wordpress
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_USERNAME=flytrap
      - WORDPRESS_PASSWORD=flytrap
      - WORDPRESS_EMAIL=hiddenstat@gmail.com
    container_name: wordpress

