apiVersion: v1
kind: Service
metadata:
  name: "myminio"
  labels:
    v1.min.io/tenant: {{ .Values.tenant.name }}
spec:
  type: "ClusterIP"
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    v1.min.io/tenant: {{ .Values.tenant.name }}
