version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
      MINIO_DEFAULT_BUCKETS: mybucket:public
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
