scope: pg-cluster
namespace: /service/
name: patroni2

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni2:8008

etcd3:
  hosts: etcd:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    postgresql:
      use_pg_rewind: true
      use_slots: true
  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni2:5432
  data_dir: /data
  use_pg_rewind: true
  parameters:
    password_encryption: scram-sha-256
    max_connections: 100
    shared_buffers: 256MB
    effective_cache_size: 1GB
    maintenance_work_mem: 64MB
    checkpoint_completion_target: 0.9
    wal_buffers: 16MB
    default_statistics_target: 100
    random_page_cost: 1.1
    effective_io_concurrency: 200
    work_mem: 4MB
    min_wal_size: 1GB
    max_wal_size: 4GB
  pg_hba:
    # 必须与 parameters.password_encryption 一致（scram-sha-256）
    - host all all 0.0.0.0/0 scram-sha-256
    - host replication replicator 0.0.0.0/0 scram-sha-256
  authentication:
    superuser:
      username: postgres
      password: flytrap
    replication:
      username: replicator
      password: replicator
