#!/bin/bash
# 根据 .env 生成 keepalived/keepalived.conf
# 每台节点执行一次，NODE_ID / KEEPALIVED_PRIORITY / KEEPALIVED_STATE 在 .env 中按节点配置

set -e
cd "$(dirname "$0")/.."
[ -f .env ] || { echo "缺少 .env，请从 .env.example 复制并填写"; exit 1; }
source .env

# 默认：节点1 为 MASTER 优先级最高，2/3 为 BACKUP
export KEEPALIVED_STATE="${KEEPALIVED_STATE:-BACKUP}"
export KEEPALIVED_PRIORITY="${KEEPALIVED_PRIORITY:-100}"
export KEEPALIVED_INTERFACE="${KEEPALIVED_INTERFACE:-eth0}"
export KEEPALIVED_ROUTER_ID="${KEEPALIVED_ROUTER_ID:-51}"
export KEEPALIVED_AUTH_PASS="${KEEPALIVED_AUTH_PASS:-secret_vrrp_pass}"
export VIP_PREFIX="${VIP_PREFIX:-24}"

# 根据 NODE_ID 设置默认 MASTER 与优先级（可被 .env 覆盖）；支持 1～6 节点
case "${NODE_ID}" in
  1) KEEPALIVED_STATE="${KEEPALIVED_STATE:-MASTER}"; KEEPALIVED_PRIORITY="${KEEPALIVED_PRIORITY:-103}" ;;
  2) KEEPALIVED_STATE="${KEEPALIVED_STATE:-BACKUP}"; KEEPALIVED_PRIORITY="${KEEPALIVED_PRIORITY:-102}" ;;
  3) KEEPALIVED_STATE="${KEEPALIVED_STATE:-BACKUP}"; KEEPALIVED_PRIORITY="${KEEPALIVED_PRIORITY:-101}" ;;
  4) KEEPALIVED_STATE="${KEEPALIVED_STATE:-BACKUP}"; KEEPALIVED_PRIORITY="${KEEPALIVED_PRIORITY:-100}" ;;
  5) KEEPALIVED_STATE="${KEEPALIVED_STATE:-BACKUP}"; KEEPALIVED_PRIORITY="${KEEPALIVED_PRIORITY:-99}" ;;
  6) KEEPALIVED_STATE="${KEEPALIVED_STATE:-BACKUP}"; KEEPALIVED_PRIORITY="${KEEPALIVED_PRIORITY:-98}" ;;
  *) echo "NODE_ID 应为 1～6"; exit 1 ;;
esac

export NODE_ID
export VIP

mkdir -p keepalived
envsubst '$NODE_ID $KEEPALIVED_STATE $KEEPALIVED_PRIORITY $KEEPALIVED_INTERFACE $KEEPALIVED_ROUTER_ID $KEEPALIVED_AUTH_PASS $VIP $VIP_PREFIX' \
  < keepalived/keepalived.conf.tpl > keepalived/keepalived.conf
echo "已生成 keepalived/keepalived.conf (STATE=$KEEPALIVED_STATE PRIORITY=$KEEPALIVED_PRIORITY)"
cat keepalived/keepalived.conf
